version: '3'
services:
    backend:
        env_file:
            - config-local.env
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./src:/app
        command: "gunicorn entry_api:api -b 0.0.0.0:8080 --reload"
